name: Update Pac-Man Contribution Graph

on:
  schedule:       # run automatically every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:   # allow manual trigger
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate Pac-Man graph (dark theme only)
        uses: AndreRuperto/svg-pacman-contributions@main
        with:
          github_user_name: S-DAw   # 👈 force your username
          github_token: ${{ secrets.GITHUB_TOKEN }}
          theme: github-dark
          output_directory: dist

      - name: Publish SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
